updated feedtime validation
mlhaus/KCC-Java2-Mon-Wed pull request #25
Opened 2020-10-21 18:04 UTC by Neiftly

changed the validator to include not allowing future dates.

2020-10-25 19:11 UTC, mlhaus commented on src/test/java/edu/kcc/animal/AnimalTest.java
> +            System.out.println(ex);
You'll want to do something like `assertTrue(true);` here.

2020-10-25 19:11 UTC, mlhaus commented on src/test/java/edu/kcc/animal/AnimalTest.java
> +            System.out.println(ex);
You need to include an assert statement here.

2020-10-25 19:12 UTC, mlhaus requested changes
Missing assert statements

2020-10-28 18:34 UTC, Neiftly commented
I think I have updated the pull request with new commits.

2020-10-28 19:09 UTC, merged