Created testSetName
mlhaus/KCC-Java2-Mon-Wed pull request #26
Opened 2020-10-21 18:15 UTC by ChaseMartinCRF01

2020-10-21 18:44 UTC, ChaseMartinCRF01 commented
Added testCompareTo()

2020-10-25 19:13 UTC, mlhaus commented on src/test/java/edu/kcc/animal/AnimalTest.java
> +        int result = animal.compareTo(other);
You're comparing null to null. You need to compare two Animal objects with data.

2020-10-25 19:13 UTC, mlhaus requested changes
Don't compare null to null.

2020-10-28 19:11 UTC, mlhaus commented on src/test/java/edu/kcc/animal/AnimalTest.java
> +    private static final String GOOD_SPECIES = "Artiodactyla ";
I mentioned that we're only doing dogs and cats.

2020-10-28 19:15 UTC, merged