created testSetFixed validator
mlhaus/KCC-Java2-Mon-Wed pull request #32
Opened 2020-10-21 18:44 UTC by hailzrene

2020-10-25 19:28 UTC, mlhaus commented on src/test/java/edu/kcc/animal/AnimalTest.java
> +        instance.setFixed(fixed);
The default value for fixed is false. Why are you trying to set false to false? Set false to true.

2020-10-25 19:29 UTC, mlhaus requested changes
I'd like this test to verify that an unfixed animal can be set to fixed -- false to true.

2020-10-25 23:55 UTC, hailzrene commented on src/test/java/edu/kcc/animal/AnimalTest.java
> +        instance.setFixed(fixed);
I have fixed it but am getting an error when trying to push it through again, is there a different method to upload my changes?

2020-10-26 00:23 UTC, mlhaus commented on src/test/java/edu/kcc/animal/AnimalTest.java
> +        instance.setFixed(fixed);
Try adding and commiting your changes first. Then pull all of the changes from my repo with `git pull upstream main`. Then do a push to your repo.

2020-10-28 19:15 UTC, hailzrene commented
This has the fixed version of last weeks pull as well as this weeks due to the pom.xml error.

2020-10-28 19:20 UTC, merged