Addition of Gender Method Tests
mlhaus/KCC-Java2-Mon-Wed pull request #35
Opened 2020-10-22 03:20 UTC by WVinson7

testGetGender()
testSetGender()
testSetGenderBad()
testSetGenderBadMaleToFemale()

2020-10-25 19:45 UTC, mlhaus commented on src/test/java/edu/kcc/animal/AnimalTest.java
> +        String original = GOOD_GENDER;
The original gender is actually unknown. You would have to set the gender to GOOD_GENDER first to have this work.

2020-10-25 19:47 UTC, mlhaus commented on src/test/java/edu/kcc/animal/AnimalTest.java
> +            if(animal.getGender() == originalEntry){
Substitute the if statement with a fail statement -- if the program allows us to set the gender from male to female we need the test to fail.

2020-10-25 19:47 UTC, mlhaus requested changes
See comments for requested changes.

2020-10-28 19:02 UTC, WVinson7 commented on src/test/java/edu/kcc/animal/AnimalTest.java
> +        String original = GOOD_GENDER;
@Test
    public void testSetGenderBad() {
        setUp();
        String gender = "vegetable";
        try{
            animal.setGender(gender);
            fail("Gender not valid.");
        }
        catch (IllegalArgumentException iae){
            assertEquals(gender, animal.getGender());
        }
    }

Like this?

2020-10-28 19:03 UTC, WVinson7 commented on src/test/java/edu/kcc/animal/AnimalTest.java
> +            if(animal.getGender() == originalEntry){
@Test
    public void testSetGenderBad() {
        setUp();
        String gender = "vegetable";
        try{
            animal.setGender(gender);
            fail("Gender not valid.");
        }
        catch (IllegalArgumentException iae){
            assertEquals(gender, animal.getGender());
        }
    }

The validator wasn't written yet. Now it is! 👍

2020-10-31 01:01 UTC, merged